                                            Classifiication Problems with Sklearn
Classification problem is that type of problem that is there to preict a discrete value that whether a tumor is malignant or not, if the condition of a car is good or not, whether there is diabetes present or not and whether a student will pass or fail the exam and so on. 

                                    Preparing Data for Classification Problems 

Like regression here also we have to first convert the data into a specific format before it can be used to train the classification algorithms. 

In [103]:
import pandas as pd 
import numpy as np 
import seaborn as sns 

The data used is of the Bank Customer Churn Prediction which basically has the record of the customers who left the bank six months after various information is recorded about them. 

In [104]:
churn_df = pd.read_csv("Bank_Customer_Churn_Prediction.csv") 
churn_df  

# Here 1 stands for those who have exited and 0 for those who have not exited  

customer_id  credit_score  country  gender  age  tenure    balance  \
0        15634602           619   France  Female   42       2       0.00   
1        15647311           608    Spain  Female   41       1   83807.86   
2        15619304           502   France  Female   42       8  159660.80   
3        15701354           699   France  Female   39       1       0.00   
4        15737888           850    Spain  Female   43       2  125510.82   
...           ...           ...      ...     ...  ...     ...        ...   
9995     15606229           771   France    Male   39       5       0.00   
9996     15569892           516   France    Male   35      10   57369.61   
9997     15584532           709   France  Female   36       7       0.00   
9998     15682355           772  Germany    Male   42       3   75075.31   
9999     15628319           792   France  Female   28       4  130142.79   

      products_number  credit_card  active_member  estimated_salary  churn  
0                   1            1              1         101348.88      1  
1                   1            0              1         112542.58      0  
2                   3            1              0         113931.57      1  
3                   2            0              0          93826.63      0  
4                   1            1              1          79084.10      0  
...               ...          ...            ...               ...    ...  
9995                2            1              0          96270.64      0  
9996                1            1              1         101699.77      0  
9997                1            0              1          42085.58      1  
9998                2            1              0          92888.52      1  
9999                1            1              0          38190.78      0  

[10000 rows x 12 columns]

In [105]:
churn_df.head() 
# Top 5 columns from the data 

customer_id  credit_score country  gender  age  tenure    balance  \
0     15634602           619  France  Female   42       2       0.00   
1     15647311           608   Spain  Female   41       1   83807.86   
2     15619304           502  France  Female   42       8  159660.80   
3     15701354           699  France  Female   39       1       0.00   
4     15737888           850   Spain  Female   43       2  125510.82   

   products_number  credit_card  active_member  estimated_salary  churn  
0                1            1              1         101348.88      1  
1                1            0              1         112542.58      0  
2                3            1              0         113931.57      1  
3                2            0              0          93826.63      0  
4                1            1              1          79084.10      0

The output shows the dtaset contain the information such as the  customer_id, geography, gender, age, etc.  
We do not need the RowNumber, Customerid, and surname Columns in pur dataset sice they do not help in predicting if a customer will churn or not. 

In [106]:
churn_df = churn_df.drop(['customer_id'], axis = 1)  
churn_df

credit_score  country  gender  age  tenure    balance  products_number  \
0              619   France  Female   42       2       0.00                1   
1              608    Spain  Female   41       1   83807.86                1   
2              502   France  Female   42       8  159660.80                3   
3              699   France  Female   39       1       0.00                2   
4              850    Spain  Female   43       2  125510.82                1   
...            ...      ...     ...  ...     ...        ...              ...   
9995           771   France    Male   39       5       0.00                2   
9996           516   France    Male   35      10   57369.61                1   
9997           709   France  Female   36       7       0.00                1   
9998           772  Germany    Male   42       3   75075.31                2   
9999           792   France  Female   28       4  130142.79                1   

      credit_card  active_member  estimated_salary  churn  
0               1              1         101348.88      1  
1               0              1         112542.58      0  
2               1              0         113931.57      1  
3               0              0          93826.63      0  
4               1              1          79084.10      0  
...           ...            ...               ...    ...  
9995            1              0          96270.64      0  
9996            1              1         101699.77      0  
9997            0              1          42085.58      1  
9998            1              0          92888.52      1  
9999            1              0          38190.78      0  

[10000 rows x 11 columns]

                                         Dividing Data into Features and Labels 
We have to divide the data into features and labels. The features set that is the Z in the following script contains all the columns except the Exited Columns. on the other hand, the labels set that is the y contains only the Exited columns. 

In [107]:
x = churn_df.drop(['churn'], axis = 1) 
x  
# The churn column has beenn removed 

credit_score  country  gender  age  tenure    balance  products_number  \
0              619   France  Female   42       2       0.00                1   
1              608    Spain  Female   41       1   83807.86                1   
2              502   France  Female   42       8  159660.80                3   
3              699   France  Female   39       1       0.00                2   
4              850    Spain  Female   43       2  125510.82                1   
...            ...      ...     ...  ...     ...        ...              ...   
9995           771   France    Male   39       5       0.00                2   
9996           516   France    Male   35      10   57369.61                1   
9997           709   France  Female   36       7       0.00                1   
9998           772  Germany    Male   42       3   75075.31                2   
9999           792   France  Female   28       4  130142.79                1   

      credit_card  active_member  estimated_salary  
0               1              1         101348.88  
1               0              1         112542.58  
2               1              0         113931.57  
3               0              0          93826.63  
4               1              1          79084.10  
...           ...            ...               ...  
9995            1              0          96270.64  
9996            1              1         101699.77  
9997            0              1          42085.58  
9998            1              0          92888.52  
9999            1              0          38190.78  

[10000 rows x 10 columns]

In [108]:
y= churn_df['churn'] 
y 
# This is the churn column which shows that 

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: churn, Length: 10000, dtype: int64

In [109]:
x.head() 

credit_score country  gender  age  tenure    balance  products_number  \
0           619  France  Female   42       2       0.00                1   
1           608   Spain  Female   41       1   83807.86                1   
2           502  France  Female   42       8  159660.80                3   
3           699  France  Female   39       1       0.00                2   
4           850   Spain  Female   43       2  125510.82                1   

   credit_card  active_member  estimated_salary  
0            1              1         101348.88  
1            0              1         112542.58  
2            1              0         113931.57  
3            0              0          93826.63  
4            1              1          79084.10

In [110]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: churn, dtype: int64

                                    Converting the Categorical Data into the Numerical data 
For Classification problems too, we need to convert the categorical data to the nuerical data. This helps in easy implementation of the algorithm. 

In [111]:
# Presenting the numerical data  
numerical = x.drop(['country', 'gender'], axis = 1) 
numerical.head() 

# Country and gender has been removed from the table dataset 

credit_score  age  tenure    balance  products_number  credit_card  \
0           619   42       2       0.00                1            1   
1           608   41       1   83807.86                1            0   
2           502   42       8  159660.80                3            1   
3           699   39       1       0.00                2            0   
4           850   43       2  125510.82                1            1   

   active_member  estimated_salary  
0              1         101348.88  
1              1         112542.58  
2              0         113931.57  
3              0          93826.63  
4              1          79084.10

In [112]:
# Presenting the categorical data  '
categorical = x.filter(['country', 'gender']) 
categorical.head() 

country  gender
0  France  Female
1   Spain  Female
2  France  Female
3  France  Female
4   Spain  Female

In [113]:
# we have to use the one hot encoding approach to convert the categorica; data into the numerical data  
import pandas as pd 
cat_numerical = pd.get_dummies(categorical, drop_first= True).astype(int)
cat_numerical

country_Germany  country_Spain  gender_Male
0                   0              0            0
1                   0              1            0
2                   0              0            0
3                   0              0            0
4                   0              1            0
...               ...            ...          ...
9995                0              0            1
9996                0              0            1
9997                0              0            0
9998                1              0            1
9999                0              0            0

[10000 rows x 3 columns]

In [114]:
# Now we need to cancatenate the numerical and the categorical converted numerical data  in one tablle 
x= pd.concat([numerical, cat_numerical], axis = 1) 
x 

credit_score  age  tenure    balance  products_number  credit_card  \
0              619   42       2       0.00                1            1   
1              608   41       1   83807.86                1            0   
2              502   42       8  159660.80                3            1   
3              699   39       1       0.00                2            0   
4              850   43       2  125510.82                1            1   
...            ...  ...     ...        ...              ...          ...   
9995           771   39       5       0.00                2            1   
9996           516   35      10   57369.61                1            1   
9997           709   36       7       0.00                1            0   
9998           772   42       3   75075.31                2            1   
9999           792   28       4  130142.79                1            1   

      active_member  estimated_salary  country_Germany  country_Spain  \
0                 1         101348.88                0              0   
1                 1         112542.58                0              1   
2                 0         113931.57                0              0   
3                 0          93826.63                0              0   
4                 1          79084.10                0              1   
...             ...               ...              ...            ...   
9995              0          96270.64                0              0   
9996              1         101699.77                0              0   
9997              1          42085.58                0              0   
9998              0          92888.52                1              0   
9999              0          38190.78                0              0   

      gender_Male  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
9995            1  
9996            1  
9997            0  
9998            1  
9999            0  

[10000 rows x 11 columns]

                                        Dividing the Data into Tranining and Test Splits 
Here, we divide the data into two sets, the training set and the testing set. The dataset is trained via the training set and evaluated on the test set.  

To split the data into train and test functions, we use the train_test-split() function from Sklearn library. There is 80 percent training set and 20 percent testing set. 

In [115]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.20 , random_state = 0) 

In [116]:
x_train # data on which the model is trained 

credit_score  age  tenure    balance  products_number  credit_card  \
7389           667   34       5       0.00                2            1   
9275           427   42       1   75681.52                1            1   
2995           535   29       2  112367.34                1            1   
5316           654   40       5  105683.63                1            1   
356            850   57       8  126776.30                2            1   
...            ...  ...     ...        ...              ...          ...   
9225           594   32       4  120074.97                2            1   
4859           794   22       4  114440.24                1            1   
3264           738   35       5  161274.05                2            1   
9845           590   38       9       0.00                2            1   
2732           623   48       1  108076.33                1            1   

      active_member  estimated_salary  country_Germany  country_Spain  \
7389              0         163830.64                0              1   
9275              1          57098.00                1              0   
2995              0         185630.76                0              0   
5316              0         173617.09                0              1   
356               1         132298.49                0              1   
...             ...               ...              ...            ...   
9225              1         162961.79                1              0   
4859              1         107753.07                0              1   
3264              0         181429.87                0              0   
9845              1         148750.16                0              1   
2732              0         118855.26                1              0   

      gender_Male  
7389            0  
9275            1  
2995            0  
5316            1  
356             0  
...           ...  
9225            0  
4859            0  
3264            1  
9845            0  
2732            0  

[8000 rows x 11 columns]

In [117]:
x_test # data on which model is tested

credit_score  age  tenure    balance  products_number  credit_card  \
9394           597   35       8  131101.04                1            1   
898            523   40       2  102967.41                1            1   
2398           706   42       8   95386.82                1            1   
5906           788   32       4  112079.58                1            0   
2343           706   38       5  163034.82                2            1   
...            ...  ...     ...        ...              ...          ...   
1037           625   24       1       0.00                2            1   
2899           586   35       7       0.00                2            1   
9549           578   36       1  157267.95                2            1   
2740           650   34       4  142393.11                1            1   
6690           573   30       8  127406.50                1            1   

      active_member  estimated_salary  country_Germany  country_Spain  \
9394              1         192852.67                1              0   
898               0         128702.10                0              0   
2398              1          75732.25                0              1   
5906              0          89368.59                0              0   
2343              1         135662.17                1              0   
...             ...               ...              ...            ...   
1037              1         180969.55                0              0   
2899              0          70760.69                0              0   
9549              0         141533.19                0              1   
2740              1          11276.48                1              0   
6690              0         192950.60                1              0   

      gender_Male  
9394            0  
898             0  
2398            0  
5906            1  
2343            1  
...           ...  
1037            0  
2899            0  
9549            1  
2740            1  
6690            1  

[2000 rows x 11 columns]

In [118]:
y_train  # data on which model is trained 

7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: churn, Length: 8000, dtype: int64

In [119]:
y_test # Data on which model is tested 

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: churn, Length: 2000, dtype: int64

                                                   Data Scaling and Normalization 
The last step before the data is passed to machine learning algorithm is that the data is made to scale.    Beacuse some values in the data are too small and some are too large, so its necessary to scale the data to convert the data into a uniform scale. 

In [120]:
# we use the function of Standard Scaler Preprocessing to scale the data  

from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()  

x_train = sc.fit_transform(x_train) 
x_test = sc.transform(x_test)  

So basically, by applying the above data, we have converted the dat into a step that can be used to train the machine learning algorithms for classification from the Sklearn library. 

                                                  Logistic Regression 

Logistic Regression is a linear model which makes the classification by passing the output of a linear regression by a sigmoid function. The process of training and making the predictions with logistic regression is as :  

In [121]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression() 

classifier = model.fit(x_train, y_train) 
classifier 

LogisticRegression()

In [122]:
y_pred = classifier.predict(x_test) 
y_pred 

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

Once we have trained a model and have to make predictions based on the test set, we have to know how weel our model performs.  
There are various metrics to evaluate a classification method.  Some most commonly used calssification metrics are F1, recall, precision,  accuracy and confusion matrix. 

True Negative : True negatives are those values which were in real the false values and model also predicted them as the false values. 

True Positive : True positives are those values which are in real true values and the model also predicted them as the true values. 

False Negatives : False negatives are those which are actually true but are predicted false by the ml model. 

False Positive : Labels that are actually false but are prediccted true by the model are called false positives.  

The ordered and the structured way of writing the positives and negatives is known as the Confusion Matrix.  

                                                        Precision 
Another way to analyze a classification algorithm is by calculating the precision which is basically obtained by dividing the true positives by the sum of true positive and false positive.  

                         Precision = true Positive / (true positive + false positive)

                                                                Recall 
Recall is calculated by dividing the true positives by the sum of true positives and false negatives.  
             
                                 recall = true positive / (true positive + false negative)

                                                    F1 Measure 
F1 Measure is simply the harmonic mean of the preccision and the recall. It is calculated as :  
                                 
                                 F1 Measure = 2[(precesion * recall) / (precesion +  recall)] 

                                                         Accuracy 
Accuracy refers to the number of correctly predicted labels divided by the total number of observations in the dataset.  

                                             Accuracy = (tp + tn) / (tp + tn + fp + fn)

In [123]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

print("The confusion Matrix\n", confusion_matrix(y_test, y_pred)) 

print("The Classification Report: ", classification_report(y_test, y_pred)) 

print("The Accuracy Score: ", accuracy_score(y_test, y_pred)) 

# The record showws that the 81 percent of the  records in the test set, logistic regression correctly predicted whether a customer will leave the bank or no

The confusion Matrix
 [[1526   69]
 [ 309   96]]
The Classification Report:                precision    recall  f1-score   support

           0       0.83      0.96      0.89      1595
           1       0.58      0.24      0.34       405

    accuracy                           0.81      2000
   macro avg       0.71      0.60      0.61      2000
weighted avg       0.78      0.81      0.78      2000

The Accuracy Score:  0.811


                                                    KNN Classifier 
KNN stands for the K nearest neighbors.  KNN is a lazy algorithm which is based oon finding the Euclidean distance betweenn the different data points. 

The process of training and testing is same as logistic regression. For training, we need to call the fit() method and for testing we need to call the predict() method.  

the code for showing the process of training, testing and evaluating the KNN Classification is as : 

In [124]:
from sklearn.neighbors import KNeighborsClassifier 

model = KNeighborsClassifier(n_neighbors = 5)  

classifier = model.fit(x_train, y_train) 
classifier

KNeighborsClassifier()

In [125]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [126]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

print("The Classificartion Report: ", classification_report(y_test, y_pred))

print("The Confusion matrix: ", confusion_matrix(y_test, y_pred)) 

print("The Accuracy Score: ", accuracy_score(y_test, y_pred)) 

# Here the accuracy iis around to be 0.827 which is around 82 percent 

The Classificartion Report:                precision    recall  f1-score   support

           0       0.86      0.93      0.90      1595
           1       0.61      0.41      0.49       405

    accuracy                           0.83      2000
   macro avg       0.73      0.67      0.69      2000
weighted avg       0.81      0.83      0.81      2000

The Confusion matrix:  [[1486  109]
 [ 237  168]]
The Accuracy Score:  0.827


                                                Random Forest Classifier 

Like the random Forest Regressor, the Random Forest Classifier is a tree based algorithm that converts the features into the tree nodes and then uses the entropy loss to make the classification predictions.  

The Random Forest Classifier csklearn.ensemble an be used to implement the random forest regressor algorithm in Python.  

In  Random forest we use the random_state and the n_estimators which are important parameters when configuring the Random Forest Classifer or even a Regressor. 

                                                        random_state  
The random_state parameter controla the randomness of the model's training process. 
In the random_stae, the randomness is used to select the data samples and features for each individual decision tree. 
It makes the result productive. 

                                                    n_estimators 
The n_estimators parametrs defines the number of decision trees in the forest.  A Random Forest is an ensemble learning method that builds many independent decision trees and merges their predictions to get a more accurate and stable result. 

More number of trees generally help in having a more robust and better performing model as the ensemble averages out individual tree errors more effectively. 

In [127]:
from sklearn.ensemble import RandomForestClassifier 

model = RandomForestClassifier(random_state = 42, n_estimators = 500) 

classifier = model.fit(x_train, y_train) 

classifier

RandomForestClassifier(n_estimators=500, random_state=42)

In [128]:
y_pred = classifier.predict(x_test) 
y_pred 

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [129]:
y_prob = classifier.predict_proba(x_test)[:,1]  
y_prob 

array([0.328, 0.178, 0.162, ..., 0.082, 0.32 , 0.236], shape=(2000,))

In [130]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score

print("The Confusion matrix: ", confusion_matrix(y_test, y_pred)) 

print("The classification Report; ", classification_report(y_test, y_pred)) 

print("The Accuracy Score: ", accuracy_score(y_test, y_pred)) 

print("ROC-AUC Score: ", roc_auc_score(y_test, y_prob))  

# Here the accuracy comes out to be 0.865 which is around 86 percent 

The Confusion matrix:  [[1521   74]
 [ 196  209]]
The classification Report;                precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.74      0.52      0.61       405

    accuracy                           0.86      2000
   macro avg       0.81      0.73      0.76      2000
weighted avg       0.86      0.86      0.86      2000

The Accuracy Score:  0.865
ROC-AUC Score:  0.8717194937884594


                                        Support Vector Classification 
The Support vector machine is a classification as well as the regression algorithms which minimizes the error between the actual predictions and the predicted predictions by maximizing the distance between the hyper planes that contain the data for various records.  

In [131]:
from sklearn import svm 
model = svm.SVC() 

classifier = model.fit(x_train, y_train) 
classifier 

SVC()

In [132]:
y_pred = classifier.predict(x_test) 
y_pred 

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [133]:
# Evaluating the algorithm  

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

print("The Confusion matrix : ", confusion_matrix(y_test, y_pred)) 

print("The Classification Report : ", classification_report(y_test, y_pred)) 

print("The Accuracy Score: ", accuracy_score(y_test, y_pred))  

# The accuracy comes oout to be around 86 percent 

The Confusion matrix :  [[1547   48]
 [ 225  180]]
The Classification Report :                precision    recall  f1-score   support

           0       0.87      0.97      0.92      1595
           1       0.79      0.44      0.57       405

    accuracy                           0.86      2000
   macro avg       0.83      0.71      0.74      2000
weighted avg       0.86      0.86      0.85      2000

The Accuracy Score:  0.8635


                                                 K Fold Cross Validation 
We can also perform the K fold cross validation for classification models just like regression models. We can use the cross_val_score() function from the sklearn.model_selection  for the classification algorithm, we need to pass the classification metrics. 
like for example, we need to pass the accuracy for the scoring attribute. 

In [134]:
from sklearn.model_selection import cross_val_score 

print(cross_val_score(classifier, x,y, cv = 5, scoring = 'accuracy'))

[0.796  0.796  0.7965 0.7965 0.7965]


                                            Predicting a Single Value 
Here, we have to make the prediction of a single customer record and see if he will leave the bank after 6 months or not. 

In [135]:
churn_df.loc[100] 

credit_score              665
country                France
gender                 Female
age                        40
tenure                      6
balance                   0.0
products_number             1
credit_card                 1
active_member               1
estimated_salary    161848.03
churn                       0
Name: 100, dtype: object

here the data shows that the customer did not exit the bank since the value of the churn attribute is equal to 0. 

In [136]:
# training the Random Forest Algorithm 

single_record = sc.transform(x.values[100].reshape(1,-1)) 

predicted_churn = classifier.predict(single_record) 

print(predicted_churn) 

# Here its correct as the value of the predicted churn for the 100th value is equal to 0 which is correct. 
# The customer will not leave tha bank after 6 months. 

[0]


c:\Users\91981\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


                                                     Exercise Questions

Q1.    
Among the following, which one is not an example of
classification outputs?

A. True

B. Red

C. Male

D. None of the above

Ans.  D. None of the above 

Q2.    
Which of the following metrics is used for unbalanced
classification datasets?

A. Accuracy

B. F1

C. Precision

D. Recall

Ans.  C. Precesion 

Q3.   Among the following functions, which one is used to convert
categorical values to one-hot encoded numerical values?

A. pd.get_onehot()

B. pd.get_dummies()

C. pd.get_numeric()

D. All of the above

Ans.  B. pd.get_dummies() 

Q4.  Using the  iris  dataset from the Seaborn library, train a
classification algorithm of your choice, which predicts the
species of the iris plant. Perform all the preprocessing steps.

In [137]:
# By using hhe iris dataset, train a classsification algotithm to predict the species of plant  

import pandas as pd 
import numpy as np 
import seaborn as sns 

In [138]:
iris_df =sns.load_dataset('iris') 
iris_df 

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [139]:
iris_df.head() 
# Top 5 values of the dataset 

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [158]:
# dividing the data into the labels or features or we can say that its divided into the dependent or independent features 
x = iris_df.drop(['species'], axis = 1) 
y = iris_df['species'] 

In [159]:
x # The dataset x is there which does not contain species data 

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [160]:
y # The data y which contains only the species data 

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [161]:
from sklearn.model_selection import train_test_split  

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0) 

In [162]:
x_train # data on which model is trained 

sepal_length  sepal_width  petal_length  petal_width
137           6.4          3.1           5.5          1.8
84            5.4          3.0           4.5          1.5
27            5.2          3.5           1.5          0.2
127           6.1          3.0           4.9          1.8
132           6.4          2.8           5.6          2.2
..            ...          ...           ...          ...
9             4.9          3.1           1.5          0.1
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
117           7.7          3.8           6.7          2.2
47            4.6          3.2           1.4          0.2

[120 rows x 4 columns]

In [163]:
x_test # data on which model is tested 

sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2
100           6.3          3.3           6.0          2.5
40            5.0          3.5           1.3          0.3
86            6.7          3.1           4.7          1.5
76            6.8          2.8           4.8          1.4
71            6.1          2.8           4.0          1.3
134           6.1          2.6           5.6          1.4
51            6.4          3.2           4.5          1.5
73            6.1          2.8           4.7          1.2
54            6.5          2.8           4.6          1.5
63            6.1          2.9           4.7          1.4
37            4.9          3.6           1.4          0.1
78            6.0          2.9           4.5          1.5
90            5.5          2.6           4.4          1.2
45            4.8          3.0           1.4          0.3
16            5.4          3.9           1.3          0.4
121           5.6          2.8           4.9          2.0
66            5.6          3.0           4.5          1.5
24            4.8          3.4           1.9          0.2
8             4.4          2.9           1.4          0.2
126           6.2          2.8           4.8          1.8
22            4.6          3.6           1.0          0.2
44            5.1          3.8           1.9          0.4
97            6.2          2.9           4.3          1.3
93            5.0          2.3           3.3          1.0
26            5.0          3.4           1.6          0.4

In [164]:
y_train # data on which model is trained 

137     virginica
84     versicolor
27         setosa
127     virginica
132     virginica
          ...    
9          setosa
103     virginica
67     versicolor
117     virginica
47         setosa
Name: species, Length: 120, dtype: object

In [165]:
y_test # Data on which model is tested 

114     virginica
62     versicolor
33         setosa
107     virginica
7          setosa
100     virginica
40         setosa
86     versicolor
76     versicolor
71     versicolor
134     virginica
51     versicolor
73     versicolor
54     versicolor
63     versicolor
37         setosa
78     versicolor
90     versicolor
45         setosa
16         setosa
121     virginica
66     versicolor
24         setosa
8          setosa
126     virginica
22         setosa
44         setosa
97     versicolor
93     versicolor
26         setosa
Name: species, dtype: object

In [166]:
# Now comes the scaling of the data   
from sklearn.preprocessing import StandardScaler 
sc= StandardScaler() 

# Scaling the data 
x_train = sc.fit_transform(x_train) 
x_test = sc.transform(x_test)

In [167]:
# Implementing the ML Model 
from sklearn.ensemble import RandomForestClassifier 
model = RandomForestClassifier(random_state = 42, n_estimators = 500) 

classifier = model.fit(x_train, y_train) 
classifier 

RandomForestClassifier(n_estimators=500, random_state=42)

In [168]:
y_pred = classifier.predict(x_test) 
y_pred 

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa'], dtype=object)

In [169]:
y_prob = classifier.predict_proba(x_test)[:,1]
y_prob 

array([0.016, 0.952, 0.002, 0.002, 0.   , 0.006, 0.   , 0.99 , 0.908,
       0.996, 0.444, 0.99 , 0.99 , 0.958, 0.994, 0.   , 0.966, 0.992,
       0.002, 0.002, 0.158, 0.986, 0.   , 0.01 , 0.172, 0.   , 0.   ,
       0.998, 0.952, 0.   ])

In [ ]:
# Now comes the evaluation of the ML Model  
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score 

print("The classification Report:", classification_report(y_test, y_pred)) 

print("Confusion Matrix:", confusion_matrix(y_test, y_pred)) 

print("Accuracy Score:", accuracy_score(y_test, y_pred))

# Here the acuracy score is 100 percent  

The classification Report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix: [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy Score: 1.0


In [ ]:
# Now comes the prediction part 
iris_df.iloc[100]

# The 100th species is virginica 

sepal_length          6.3
sepal_width           3.3
petal_length          6.0
petal_width           2.5
species         virginica
Name: 100, dtype: object

In [ ]:
# Now we do the prediction  

single_record = sc.transform(x.values[100].reshape(1,-1)) 

predicted_species = classifier.predict(single_record) 

print(predicted_species) 

# Here as we can see that the species of the 100th flwer gets predicred as virginica which is correct 

['virginica']


c:\Users\91981\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
