NumPy (Numerical Python) is a Python Library for data science and numerical computing. many advanced data science and machine learning libraries require data to be in the form of NumPy arrays befor it can be prcessed

NumPy Library has several advantages like the : 

1. NumPy arrays are much faster for insertion, deletion, updation and radeing of the data. 
2. NumPy arrays contain the advanced broadcasting functionalties compared with regular Python arrays. 
3. NumPy array comes with a lot of methods that support advanced arithmetic and linear alegebra options. 
4. NumPy provides advanced multi dimensional array slicing capabilities. 

In [2]:
import numpy as np 
num_list = [10,20,12,16,40]

num_array = np.array(num_list) 
print(num_array)

print(type(num_array))

[10 20 12 16 40]
<class 'numpy.ndarray'>


In [19]:
import numpy as np 
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape

print(nums_2d)
print(nums_2d.shape)

[[10 12 13]
 [45 32 16]
 [45 32 16]]
(3, 3)


In [25]:
nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [31]:
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


In [37]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [38]:
ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
zeros_array = np.zeros(6)
print(zeros_array)


[0. 0. 0. 0. 0. 0.]


In [44]:
zeros_array = np.zeros((6,4))

print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [48]:
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


The random.rand() function from the NumPy module can be used to create a NumPy array with uniform distribution.  

The random.randn() function is used to create the NumPy array with normal distribution. 

In [49]:
uniform_random = np.random.rand(4,5)
print(uniform_random)

# Here if we print it everytime we get different random data 

[[0.03448862 0.94313058 0.33920508 0.4987365  0.98628014]
 [0.10853555 0.57553553 0.96776274 0.10372831 0.78156686]
 [0.90716863 0.2354398  0.61155746 0.91517142 0.31829135]
 [0.97381001 0.95031887 0.5240769  0.37173054 0.52374037]]


In [52]:
normal_random = np.random.randn(4,5)
print(normal_random)

[[ 0.32218225  1.71129002 -0.72596199  1.24877226  0.19995305]
 [-0.17084573  0.67832719 -0.84353632 -1.51830751  1.72168846]
 [ 2.03026749  0.50060288 -0.32806597 -0.25375695  0.23526737]
 [ 0.92206564 -1.16910108  1.01554668  0.18698284  0.29338151]]


In [55]:
integer_random = np.random.randint(10,50,5)
print(integer_random)

[18 32 35 25 46]


In [56]:
s = np.arange(1,11)
print(s)
# Printing the array arranged 

print(s[1])
# Printing the index 2

print(s[1:9])
# Printing from the index 1 to index 98

print(s[:5])
# From the starting to the 4 index 

print(s[5:])
# from index 5 to the ending 

[ 1  2  3  4  5  6  7  8  9 10]
2
[2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [57]:
rows1 = [10,12,13]
rows2 = [45,32,16]

num_arrays = np.array([rows1, rows2])

print(num_arrays)

# Here the arrays are getting formed 

[[10 12 13]
 [45 32 16]]


Reshaping NumPy arrays : A NumPy array can be reshaped using the reshape() function. Its important to mention the product of the rows and columns in the reshaped array must be equal to the product of the rows and columns in the original array. 

In [63]:
uniform_random = np.random.rand(4,6)
uniform_random2 = uniform_random.reshape(3,8)

print(uniform_random)

print(uniform_random2)

[[0.00782895 0.41528721 0.98439    0.22217429 0.88968129 0.54453412]
 [0.48208859 0.87024624 0.07238918 0.65928467 0.82277644 0.67486152]
 [0.36311514 0.74996777 0.14064403 0.4207979  0.21483621 0.51306628]
 [0.59785669 0.36626134 0.84233194 0.69456533 0.57115853 0.69278934]]
[[0.00782895 0.41528721 0.98439    0.22217429 0.88968129 0.54453412
  0.48208859 0.87024624]
 [0.07238918 0.65928467 0.82277644 0.67486152 0.36311514 0.74996777
  0.14064403 0.4207979 ]
 [0.21483621 0.51306628 0.59785669 0.36626134 0.84233194 0.69456533
  0.57115853 0.69278934]]


Array Indexing and Slicing :  NumPy arrays can be sliced and indexed. Slicing an array means dividing an array into mutiple parts. 
NumPy arrays are indexed into multiple parts. NumPy arrays are indexed just like the normal lists. Indexes in NumPy arrays start from 0 which means that the first itemof a NumPy array is stored at the 0th index. 

In [65]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:2 , :])

[[10 12 13]
 [45 32 16]]


In [66]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:, :2])

[[10 12]
 [45 32]
 [45 32]]


In [ ]:
import numpy as np 
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[1:, 1:])

# Here we have done such a slicing that there are last 2 rows and last 2 columns 

[[32 16]
 [32 16]]


In [68]:
# Finding the sqaure root using the numpy  

nums = [10,20,30,40,50] 
np_sqr = np.sqrt(nums) 

print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [69]:
# Finding log through the elements of the list 

nums =[10,20,30,40,50] 
np_log = np.log(nums) 

print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [70]:
# the exp function through the numpy array   

nums = [10,20,30,40,50]  
np_exp = np.exp(nums) 

print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [ ]:
# findin gthe sine functions by Numpy   

nums = [10,20,30,40,50] 
np_sine = np.sin(nums) 

print(np_sine)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [72]:
# Finding the cosine functions of the numpy  

nums = [10,20,30,40,50] 
np_cos = np.cos(nums)  

print(np_cos)

[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


                                          NumPy for Linear Algebra Operations 
Data Science makes extensive use of the linear algebra. The suppot for performing the advanced linear algebra functions in a fast and eficient way.  

Hence it makes NumPy the most routinely used library in Python to be used.  

In [73]:
A = np.random.randn(4,5) 
B = np.random.randn(5,4) 

Z= np.dot(A,B) 

print(Z)

[[ 0.55594671 -1.35168968  0.19398381  0.25986245]
 [-1.84340083 -2.10336105  1.96574158  1.69568139]
 [-0.12393142  4.43226806 -2.74563266 -2.16408582]
 [-0.96189986  0.31511122  0.74023843  0.90503348]]


In [74]:
row1 = [1,2,3] 
row2 = [4,5,6] 
row3 = [7,8,9] 

nums_2d = np.array([row1, row2, row3]) 

multiply = np.multiply(nums_2d, nums_2d)  

print(multiply)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
row1 = [1,2,3] 
row2 = [4,5,6] 
row3 = [7,8,9] 

nums_2d = np.array([row1, row2, row3])  

inverse = np.linalg.inv(nums_2d)  

print(inverse) 

# Here since the detremonatn = 0 , so its showing error hence no inverse of the matrix 

LinAlgError: Singular matrix

In [80]:
import numpy as np 
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [34,21,89]

nums_2d = np.array([row1, row2, row3]) 

inverse = np.linalg.inv(nums_2d) 

print(inverse)

[[-0.13748563  0.04351158  0.01225987]
 [ 0.18942587 -0.02451973 -0.02326091]
 [ 0.00782661 -0.01083685  0.01204094]]


In [81]:
# Finding the matrix determinant 

import numpy as np 
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [34,21,89]

nums_2d = np.array([row1, row2, row3]) 

determinant = np.linalg.det(nums_2d) 

print(determinant )

-18270.99999999999


In [ ]:
# Finding the trace of a matrix  
# Trace refers to the finding of the sum of all elements along the diagonal of a matrix 

row1 = [1,2,3] 
row2 = [4,5,6]
row3 = [7,8,9] 

nums_2d = np.array([row1, row2, row3])

trace = np.trace(nums_2d) 
print(trace) 

15


                                                     Exercise Questions 

Q1. Which NumPy function is used for the element-wise
multiplication of two matrices?

A. np.dot(matrix1, matrix2)

B. np.multiply(matrix1, matrix2)

C. np.elementwise(matrix1, matrix2)

D. None of the above

Ans.  B. np.multiply(matrix1 , matrix2)

Q2.  
To generate an identity matrix of four rows and four columns,
which of the following functions can be used?

A. np.identity(4,4)

B. np.id(4,4)

C. np.eye(4,4)

D. All of the above

Ans.       
C. np.eye(4,4)

Q3.   
How to create the array of numbers 4,7,10,13,16 with NumPy:

A. np.arange(3, 16, 3)

B. np.arange(4, 16, 3)

C. np.arange(4, 15,3)

D. None of the above

Ans.  D Noone of the above 

Q4. Create a random NumPy array of five rows and four columns.
                  Using array indexing and slicing, display the items from row
                                                     three to end and column two to end.

In [ ]:
# the code for the above example is as : 

uniform_random = np.random.rand(5,4) 
print(uniform_random) 

print("Result") 

print(uniform_random[2: , 3:])

#The last 3 rows and last column 

[[0.29457312 0.52558425 0.35917983 0.13124091]
 [0.38104038 0.20583344 0.84259208 0.48128205]
 [0.82136896 0.00343349 0.93961633 0.45625028]
 [0.13370112 0.57979727 0.26001758 0.11476481]
 [0.41031428 0.9433107  0.86128052 0.08515713]]
Result
[[0.45625028]
 [0.11476481]
 [0.08515713]]
